# Window settings
[window]
padding.x = 5
padding.y = 5
opacity = 1.0
decorations = "buttonless" # For macOS

# Font settings
[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 12

# Color scheme (example)
[colors.primary]
foreground = "#0a0a0c"
background = "#0a0a0c"

[terminal]
shell = "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe"


