cursor #f0efeb
cursor_text_color #ccc4b4

foreground            #f0efeb
background            #1a1d21
selection_foreground  #1a1d21
selection_background  #b4c4bc
url_color             #b4c0c8

color0   #22262b
color1   #e5678e
color2   #64c870
color3   #faf270
color4   #a7b4bd
color5   #4b555c
color6   #b4c0c8
color7   #c5ccd2
color8   #7d8287
color9   #ff9fbd
color10  #9cf0a6
color11  #fff9a5
color12  #c9d4dc
color13  #edf7ff
color14  #f3faff
color15  #f8fcff
