# ~/.config/aerc/aerc.conf

[general]
log-level = trace
log-file = ~/Data/Mail/aerc/aerc.log
default-save-path = ~/Data/Mail/aerc/
empty-subject-warning = true

[ui]
styleset-name = rose-pine
auto-mark-read = false
border-char-vertical = " "
column-separator = "  "
dirlist-delay = 500ms
dirlist-tree = true
empty-message = "Tumbleweed"
index-columns = date<8,name<17,subject<*,flags<4
next-message-on-delete = false
pinned-tab-marker = '*'
threading-enabled = true
timestamp-format = 06-01-02 15:04
this-day-time-format = 15:04
this-week-time-format = Mon
this-year-time-format = 06-01-02
client-threads-delay = 50ms
force-client-threads = false
fuzzy-complete = true

[statusline]
status-columns = left<*,center>=,right>*
column-left = {{.Folder}}
column-center = {{.PendingKeys}} {{.TrayInfo}} {{.StatusInfo}}
column-right = {{if gt (len .From) 0}}{{(index .From 0).Address}}{{else}}No Sender{{end}} {{.Size | humanReadable}}
separator = " | "

[viewer]
text/plain = less %s
text/html = w3m -T text/html %s
image/* = xdg-open %s

[compose]
editor = sh -c 'exec /usr/bin/nvim +"set ft=mail" +"set spell" "$@"'
header-layout = To,Cc,Bcc,From,Subject
reply-to-self = true
no-attachment-warning = true
# Linux file picker (uncomment one)
# file-picker-cmd = sh -c 'printf "%s\n" "$@"' -- %s
# file-picker-cmd = fzf --multi --query="%s"

[multipart-converters]
text/html = pandoc -f markdown -t html --standalone

[filters]
text/plain = sed 's/^>\+.*/\x1b[36m&\x1b[0m/'
text/html = w3m -T text/html
application/pdf = xdg-open
image/* = catimg -w $(tput cols) -

[openers]
text/plain = nvim -R
text/html = w3m -F -I UTF-8 -T text/html -dump
message/rfc822 = xdg-open

[triggers]
# Linux notification
new-email = exec notify-send "New email from %n" "%s"

