[ui]
styleset-name = rose-pine

[Gmail]
source = imaps+oauthbearer://jeremy%40chiefgeek.io:YOUR_REFRESH_TOKEN@imap.gmail.com:993?client_id=YOUR_CLIENT_ID&client_secret=YOUR_CLIENT_SECRET&token_endpoint=https%3A%2F%2Foauth2.googleapis.com%2Ftoken
outgoing = smtps+oauthbearer://jeremy%40chiefgeek.io:YOUR_REFRESH_TOKEN@smtp.gmail.com:465?client_id=YOUR_CLIENT_ID&client_secret=YOUR_CLIENT_SECRET&token_endpoint=https%3A%2F%2Foauth2.googleapis.com%2Ftoken
default = INBOX

