#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#
###                                                                AUTOSTART                                                                      ###
#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#

#/||--------------------------------------------------------------------------------------------||\#

# NOOB-NOTE: Autostart Applications
# This section defines which applications and services will automatically start
# when you log in to your system. It ensures essential services and apps are ready
# without manual input, like video bridges, notification daemons, and desktop tools.

# Tip: Add any apps you want to run at startup here. You can remove or adjust them as needed.
# For more info, check the documentation: https://wiki.hyprland.org

#/||--------------------------------------------------------------------------------------------||\#


#/||-------------------------------------------------||\#
###                 Hyprland Ecosystem                ###
#/||-------------------------------------------------||\#


#/||-------------------------------------------------||\#
###                  Desktop Experience               ###
#/||-------------------------------------------------||\#
exec-once = hyprlock
exec-once = hypridle >> ~/hypridle.log
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprpaper
exec-once = waybar

#/||-------------------------------------------------||\#
###                  User Applications                ###
#/||-------------------------------------------------||\#

