#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#
###                                                              ENVIRONMENT                                                                      ###
#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#

#/||--------------------------------------------------------------------------------------------||\#

# NOOB-NOTE: Environment Variables and Configurations
# This script configures system settings, optimizes performance, and ensures compatibility
# with NVIDIA GPUs, Vulkan, Wayland, Steam, Electron apps, and other graphical applications.
# It includes environment variable setups for hardware acceleration, display server settings,
# and graphical optimizations, along with customized appearance and cursor settings for Wayland
# and X11 applications. Additionally, it provides tweaks for performance, compositors, and
# UI elements to improve the overall user experience and resource utilization.

#/||--------------------------------------------------------------------------------------------||\#

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
