#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#
###                                                               WINDOW RULES                                                                    ###
#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#

#/||-------------------------------------------------||\#
###                  Developer Fixes                  ###
#/||-------------------------------------------------||\#
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class ^(brave-browser)$
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class ^(spotify)$
windowrule = workspace 1 silent, match:class ^(spotify)$
