#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#
###                                                               WINDOW RULES                                                                    ###
#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#

#/||-------------------------------------------------||\#
###                  Developer Fixes                  ###
#/||-------------------------------------------------||\#
windowrule =  suppressevent maximize, class:.*
windowrulev2 = opacity 1.0 override, class:(brave-browser)
windowrulev2 = workspace 1, class:(spotifyterm)

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = suppressevent maximize, class:.*
