#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#
###                                                               WINDOW RULES                                                                    ###
#/||---------------------------------------------------------------------------------------------------------------------------------------------||\#

#/||-------------------------------------------------||\#
###                  Developer Fixes                  ###
#/||-------------------------------------------------||\#
windowrulev2 = opacity 1.0 override, class:(brave-browser)
windowrulev2 = workspace 1, class:(spotify)
