return {
  -- "epwalsh/obsidian.nvim",
  -- version = "*",
  -- lazy = false, -- Changed: Load on startup instead of lazy
  -- -- ft = "markdown", -- Removed: This was restricting it to markdown files only
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  -- },
  -- opts = {
  --   workspaces = {
  --     {
  --       name = "brain",
  --       path = "~/vaults/brain",
  --     },
  --   },
  --
  --   mappings = {
  --     -- These only work in markdown buffers
  --     ["<CR>"] = {
  --       action = function()
  --         return require("obsidian").util.smart_action()
  --       end,
  --       opts = { buffer = true, expr = true },
  --     },
  --     ["gf"] = {
  --       action = function()
  --         return require("obsidian").util.gf_passthrough()
  --       end,
  --       opts = { noremap = false, expr = true, buffer = true },
  --     },
  --     ["<leader><space>"] = {
  --       action = function()
  --         return require("obsidian").util.toggle_checkbox()
  --       end,
  --       opts = { buffer = true },
  --     },
  --   },
  --
  --   ui = {
  --     enable = false,
  --   },
  -- },
  -- -- Add global keybinds after plugin loads
  -- config = function(_, opts)
  --   require("obsidian").setup(opts)
  --
  --   -- Global keybinds (work from anywhere)
  --   vim.keymap.set('n', '<leader>oo', '<cmd>ObsidianQuickSwitch<CR>', { desc = "Obsidian: Open note" })
  --   vim.keymap.set('n', '<leader>on', '<cmd>ObsidianNew<CR>', { desc = "Obsidian: New note" })
  --   vim.keymap.set('n', '<leader>os', '<cmd>ObsidianSearch<CR>', { desc = "Obsidian: Search notes" })
  --   vim.keymap.set('n', '<leader>ob', '<cmd>ObsidianBacklinks<CR>', { desc = "Obsidian: Backlinks" })
  --   vim.keymap.set('n', '<leader>ot', '<cmd>ObsidianToday<CR>', { desc = "Obsidian: Today's note" })
  -- end,
}
